spring:
  datasource:
    username: C5320729
    password:
    url: jdbc:postgresql://localhost:5432/postgres
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: false
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true