spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: C5320729
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    enabled: true